version: '3'

services:
  app:
    build: .
    container_name: cloneflix_micro_videos_app
    image: williandarosa/codeeducationlaravel
    entrypoint: dockerize
      -template ./.docker/app/.env:.env
      -template ./.docker/app/nginx.conf:./.docker/nginx/nginx.conf
      -wait tcp://db:3306
      -timeout 40s
      ./.docker/entrypoint.sh
    environment:
      - DB_HOST=cloneflix_micro_videos_db
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - REDIS_HOST=redis
      - NGINX_HOST=cloneflix_micro_videos_app
      - NGINX_PORT=9000
    volumes:
      - .:/var/www
    networks:
      - cloneflix_micro_videos_app_networks
    depends_on:
      - db
      - redis

  nginx:
    build: .docker/nginx
    container_name: cloneflix_micro_videos_nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    networks:
      - cloneflix_micro_videos_app_networks
    depends_on:
      - app

  redis:
    image: redis:alpine
    container_name: cloneflix_micro_videos_redis
    expose:
      - 6379
    networks:
      - cloneflix_micro_videos_app_networks

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: cloneflix_micro_videos_db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    networks:
      - cloneflix_micro_videos_app_networks

networks:
  cloneflix_micro_videos_app_networks:
    driver: bridge
