version: '3'

services:
  app:
    build: .
    container_name: cloneflix_micro_videos_app
    image: williandarosa/codeeducationlaravel
    entrypoint: dockerize
      -template ./.docker/app/.env:.env
      -template ./.docker/app/.env.testing:.env.testing
      -template ./.docker/app/nginx.conf:./.docker/nginx/nginx.conf
      -wait tcp://db:3306
      -timeout 40s
      ./.docker/entrypoint.sh
    environment:
      - _DB_HOST=cloneflix_micro_videos_db
      - _DB_DATABASE=cloneflix_micro_video
      - _DB_USERNAME=root
      - _DB_PASSWORD=root
      - TEST_DB_DATABASE=cloneflix_micro_video_test
      - _REDIS_HOST=redis
      - _AWS_ACCESS_KEY_ID=$CLONEFLIX_AWS_ACCESS_KEY_ID
      - _AWS_SECRET_ACCESS_KEY=$CLONEFLIX_AWS_SECRET_ACCESS_KEY
      - _AWS_DEFAULT_REGION=us-east-1
      - _AWS_BUCKET=$CLONEFLIX_AWS_BUCKET
      - _AWS_URL=$CLONEFLIX_AWS_URL
      - NGINX_HOST=cloneflix_micro_videos_app
      - NGINX_PORT=9000
    volumes:
      - .:/var/www
    networks:
      - cloneflix_micro_videos_app_networks
    depends_on:
      - db
      - redis

  nginx:
    build: .docker/nginx
    container_name: cloneflix_micro_videos_nginx
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    networks:
      - cloneflix_micro_videos_app_networks
    depends_on:
      - app

  redis:
    image: redis:alpine
    container_name: cloneflix_micro_videos_redis
    expose:
      - 6379
    networks:
      - cloneflix_micro_videos_app_networks

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: cloneflix_micro_videos_db
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    networks:
      cloneflix_micro_videos_app_networks:
        ipv4_address: 172.18.0.21

networks:
  cloneflix_micro_videos_app_networks:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/24"
